### ISSUE TITLE
Show timestamp of last update of a dataset

### ISSUE THREAD

**Issue by hutershvili** [digiwhist/opentender-frontend#4]
I would find it very useful if the portal could show a timestamp with the date on which the dataset for a particular country was last updated. 

It might also be useful to provide an indication how often data is updated (daily, weekly, monthly, less regular).

**Comment by ffalt** [comment]
I include a "download file creation date", since these are all generated at once it will be only one for all countries, but better than no indication. 
the country data comes from various sources, so there is not one fixed update date per country. for a particular tender there is a "created" and "modified" date field on the tender page in the "Additional Information" section and of course in the downloadable data itself.
